// 釜山行 7/28 - 8/5 行程資料

const TRIP = {
  title: '釜山行',
  subtitle: '9天8夜 · 初訪韓國',
  startDate: '2026-07-28',
  endDate: '2026-08-05',
  cityFrom: 'TPE',
  cityTo: 'PUS',
  travelers: 1,
};

const HOTELS = [
  {
    id: 'h1',
    name: '海雲台區飯店',
    area: '海雲台 Haeundae',
    nights: 2,
    checkIn: '7/28 (一)',
    checkOut: '7/30 (三)',
    photo: 'haeundae',
    tag: '海景房',
    nearest: '海雲台站 (2號線) · 步行 5 分',
  },
  {
    id: 'h2',
    name: '西面站飯店',
    area: '西面 Seomyeon',
    nights: 6,
    checkIn: '7/30 (三)',
    checkOut: '8/05 (二)',
    photo: 'seomyeon',
    tag: '市區中心',
    nearest: '西面站 (1號線 / 2號線) · 步行 3 分',
  },
];

const DAYS = [
  {
    n: 1, date: '7/28', dow: '一', kind: 'arrival',
    title: '抵達釜山 · 海雲台日落',
    base: '海雲台',
    weather: '☀ 29° / 24°',
    photo: 'gimhae',
    summary: '金海機場入境 → 飯店 check-in → 海雲台沙灘散步 → 海雲台市場晚餐',
    stops: [
      { t: '15:30', name: '抵達金海機場 PUS', sub: '入境審查 + 領行李 + 換T-money', icon: 'ic_airplane_fill', tag: '抵達' },
      { t: '16:30', name: '輕軌 + 2號線到海雲台', sub: '沙上→西面→海雲台 · 約 60 分 · ₩1,600', icon: 'ic_train_line' },
      { t: '17:45', name: '飯店 Check-in', sub: '放行李 · 短暫休息', icon: 'ic_inn_line' },
      { t: '18:30', name: '海雲台沙灘 + 冬柏島散步', sub: '看 The Bay 101 夜景 · 釜山經典明信片角度', icon: 'ic_location_line', highlight: true },
      { t: '20:00', name: '海雲台市場晚餐', sub: '蔘雞湯 / 豬肉湯飯 / 蟹腳料理任選', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 2, date: '7/29', dow: '二', kind: 'normal',
    title: '海雲台一日 · 海岸線最美段',
    base: '海雲台',
    weather: '☀ 30° / 25°',
    photo: 'cheongsapo',
    summary: 'Sky Capsule → 青沙浦紅白燈塔 → 五六島 Skywalk → 廣安里看煙火橋',
    stops: [
      { t: '09:00', name: '海雲台藍線公園 Sky Capsule', sub: '迷你海岸列車 · 建議單程搭，回程走海岸步道', icon: 'ic_train_line', highlight: true, tag: '必去' },
      { t: '10:30', name: '青沙浦紅白燈塔 + 踏石觀景台', sub: '玻璃地板 20m 高 · 拍照熱點', icon: 'ic_camera_line' },
      { t: '12:30', name: '尾浦海鮮午餐', sub: '辣炒章魚 / 烤蛤蜊', icon: 'ic_utensils_line' },
      { t: '14:30', name: '五六島 Skywalk', sub: 'U字形玻璃步道伸入太平洋', icon: 'ic_location_line' },
      { t: '17:00', name: '廣安里海水浴場', sub: '逛海邊咖啡街 · 晚餐選擇多', icon: 'ic_sun_line' },
      { t: '20:00', name: '廣安大橋夜景', sub: '週末有無人機表演 · 沙灘席地而坐', icon: 'ic_sparkles_fill', highlight: true },
    ],
  },
  {
    n: 3, date: '7/30', dow: '三', kind: 'transfer',
    title: '移動到西面 · 西部老釜山',
    base: '海雲台 → 西面',
    weather: '⛅ 31° / 25°',
    photo: 'gamcheon',
    summary: '退房寄行李到西面 → 甘川洞文化村 → 札嘎其 → BIFF廣場 → 龍頭山公園',
    stops: [
      { t: '10:00', name: '退房 · 行李寄送到西面飯店', sub: '飯店或用 LugStay app · 一件約 ₩15,000', icon: 'ic_inn_line', tag: '搬家日' },
      { t: '11:00', name: '搭 2 號線到沙上換 1 號線', sub: '到土城站 6 號出口 · 約 70 分', icon: 'ic_train_line' },
      { t: '12:30', name: '甘川洞文化村', sub: '釜山版聖托里尼 · 蓋章地圖 ₩2,000', icon: 'ic_camera_line', highlight: true },
      { t: '15:00', name: '札嘎其市場 + BIFF廣場', sub: '海鮮市場 2F 現點現吃 · BIFF吃街邊小吃', icon: 'ic_utensils_line' },
      { t: '17:30', name: '龍頭山公園 + 釜山塔', sub: '看日落 + 老城區夜景', icon: 'ic_location_line' },
      { t: '19:00', name: '搭 1 號線回西面 Check-in', sub: '西面是釜山美食總部 · 晚餐找豬肉湯飯一條街', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 4, date: '7/31', dow: '四', kind: 'normal',
    title: '影島一日 · 太宗台 + 松島',
    base: '西面',
    weather: '☀ 30° / 25°',
    photo: 'songdo',
    summary: '太宗台燈塔步道 → 影島Huinnyeoul文化村 → 松島海上纜車 + 天空步道',
    stops: [
      { t: '09:30', name: '太宗台遊園列車 Danubi', sub: '燈塔 → 影島燈塔 → 太宗寺 環島約 1.5 小時', icon: 'ic_bus_line', highlight: true },
      { t: '12:30', name: '影島 Huinnyeoul 文化村', sub: '彩繪海岸村 · 海風咖啡店超多', icon: 'ic_camera_line' },
      { t: '14:00', name: '海岸壁畫午餐', sub: '推薦海景餐廳 + 鯷魚拌飯', icon: 'ic_utensils_line' },
      { t: '15:30', name: '松島龍宮雲橋', sub: '免費海上步道 · 走到岩礁島', icon: 'ic_location_line' },
      { t: '16:30', name: '松島海上纜車', sub: '單程 1.62km · 水晶艙加價 ₩4,000', icon: 'ic_location_colorwborder', highlight: true },
      { t: '19:00', name: '西面豬肉湯飯街晚餐', sub: '密陽血腸湯飯 / 浦項豬肉湯飯任選', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 5, date: '8/01', dow: '五', kind: 'daytrip',
    title: '慶州一日遊 · 千年古都',
    base: '西面 → 慶州 → 西面',
    weather: '☀ 31° / 24°',
    photo: 'gyeongju',
    summary: 'KTX 30分到慶州 → 佛國寺 → 石窟庵 → 大陵苑 → 瞻星台 → 東宮與月池夜景',
    stops: [
      { t: '08:00', name: '釜山站 KTX 到新慶州', sub: '單程 30 分 · ₩11,000 · 建議網路訂位', icon: 'ic_highspeed_rail_line', tag: '小旅行' },
      { t: '09:30', name: '佛國寺', sub: 'UNESCO世界遺產 · 韓國最美寺廟', icon: 'ic_location_line', highlight: true },
      { t: '11:30', name: '石窟庵', sub: '山上佛龕 · 從佛國寺搭 12 號公車', icon: 'ic_location_line' },
      { t: '14:00', name: '皇理團路 + 大陵苑古墳群', sub: '韓屋咖啡街 · 走進千年古墓園', icon: 'ic_camera_line' },
      { t: '17:00', name: '瞻星台 + 月精橋', sub: '東亞最古老天文台', icon: 'ic_location_line' },
      { t: '19:30', name: '東宮與月池夜景', sub: '新羅王宮遺址 · 水中倒影絕景', icon: 'ic_sparkles_fill', highlight: true },
      { t: '21:30', name: 'KTX 回釜山', sub: '末班約 22:30 · 留意班次', icon: 'ic_highspeed_rail_line' },
    ],
  },
  {
    n: 6, date: '8/02', dow: '六', kind: 'normal',
    title: '機張 + 海東龍宮寺 · 海邊朝聖',
    base: '西面',
    weather: '⛅ 30° / 25°',
    photo: 'yonggungsa',
    summary: '海東龍宮寺 → 機張市場螃蟹 → Lotte Premium Outlet → 回西面看夜景',
    stops: [
      { t: '09:30', name: '搭東海線到 OSIRIA 站', sub: '從海雲台轉接駁公車 · 約 90 分', icon: 'ic_train_line' },
      { t: '11:00', name: '海東龍宮寺', sub: '韓國最美海邊寺廟 · 108階觀音祈福', icon: 'ic_location_line', highlight: true },
      { t: '13:00', name: '機張市場帝王蟹午餐', sub: '一隻 1kg 起 · 約 ₩90,000 起跳', icon: 'ic_utensils_line', tag: '貴' },
      { t: '15:00', name: 'Lotte Premium Outlet 東釜山店', sub: '免稅退稅一次搞定 · 設計類 outlet', icon: 'ic_store_fill' },
      { t: '18:30', name: 'Centum City Spa Land', sub: '韓式汗蒸幕 ₩20,000 · 4小時上限', icon: 'ic_haedongspa', highlight: true },
      { t: '21:00', name: '西面晚餐 · 部隊鍋', sub: '推薦松亭 3 代 / 田浦巷弄小店', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 7, date: '8/03', dow: '日', kind: 'normal',
    title: '梵魚寺 + 田浦咖啡街',
    base: '西面',
    weather: '☀ 30° / 24°',
    photo: 'beomeosa',
    summary: '梵魚寺禪修晨間 → 西面美食巡禮 → 田浦咖啡街 → 釜山塔夜景',
    stops: [
      { t: '08:30', name: '1 號線到梵魚寺站', sub: '再轉 90 號公車到入口 · 約 60 分', icon: 'ic_train_line' },
      { t: '10:00', name: '梵魚寺', sub: '釜山最大山中古剎 · 千年銀杏', icon: 'ic_location_line', highlight: true },
      { t: '13:00', name: '回西面吃米腸湯飯', sub: '推薦三代家 / 草梁麥麵', icon: 'ic_utensils_line' },
      { t: '15:00', name: '田浦咖啡街 Jeonpo Cafe Street', sub: 'CNN票選亞洲必去 · 老倉庫改裝特色店', icon: 'ic_camera_line', highlight: true },
      { t: '18:00', name: '釜田市場 / 凱悅地下街', sub: '伴手禮採買 · 海苔/泡麵/燒酒', icon: 'ic_store_fill' },
      { t: '20:00', name: 'BIFC 觀景台 (免費)', sub: '63 樓看西面 + 港灣夜景', icon: 'ic_sparkles_fill' },
    ],
  },
  {
    n: 8, date: '8/04', dow: '一', kind: 'normal',
    title: '西面壓軸 · Shinsegae + 廣安里煙火',
    base: '西面',
    weather: '☀ 30° / 25°',
    photo: 'gwangalli',
    summary: '釜山博物館 → Shinsegae Centum City (世界最大百貨) → 廣安里無人機+煙火',
    stops: [
      { t: '10:00', name: '釜山博物館 (免費)', sub: '快速看完釜山 + 韓國史', icon: 'ic_info_line' },
      { t: '12:30', name: 'Shinsegae Centum City', sub: '金氏紀錄世界最大百貨 · 美食街午餐', icon: 'ic_store_fill', highlight: true, tag: '購物' },
      { t: '16:00', name: 'Lotte 西面店地下街', sub: '最後伴手禮補貨 · 樂天免稅店退稅', icon: 'ic_store_fill' },
      { t: '19:00', name: '廣安里晚餐', sub: '海邊餐廳訂窗邊位 · 看大橋打燈', icon: 'ic_utensils_line' },
      { t: '20:30', name: '廣安里無人機 + 煙火秀', sub: '週末固定演出 · 提早卡位', icon: 'ic_sparkles_fill', highlight: true, tag: '壓軸' },
    ],
  },
  {
    n: 9, date: '8/05', dow: '二', kind: 'departure',
    title: '賦歸 · 西面 → 金海機場',
    base: '西面',
    weather: '⛅ 30° / 25°',
    photo: 'bifc',
    summary: '早餐 → 退稅 → 搭輕軌到機場 → 起飛回家',
    stops: [
      { t: '08:30', name: '西面早餐 · 海雲台元祖牛骨湯', sub: '飯店附近 24h 開店', icon: 'ic_utensils_line' },
      { t: '10:00', name: '退稅 + 退 T-money 餘額', sub: 'CU/GS25 機台退稅 · T-money到便利店退', icon: 'ic_coupon_color', tag: '別忘' },
      { t: '11:30', name: '飯店退房 + 搭 2 號線到沙上', sub: '沙上轉輕軌約 5 站到機場', icon: 'ic_train_line' },
      { t: '13:00', name: '抵達金海機場 PUS', sub: '建議起飛前 2.5h 抵達 · 國際線退稅', icon: 'ic_airplane_fill' },
      { t: '15:30', name: '起飛 · 再見釜山', sub: '飛行時間約 2h20m 回台北', icon: 'ic_airplane_line' },
    ],
  },
];

Object.assign(window, { TRIP, HOTELS, DAYS });
