// 釜山行 7/28 - 8/4 行程資料

const TRIP = {
  title: '釜山行',
  subtitle: '8天7夜 · 初訪韓國',
  startDate: '2026-07-28',
  endDate: '2026-08-04',
  cityFrom: 'TPE',
  cityTo: 'PUS',
  travelers: 11,
};

const HOTELS = [
  {
    id: 'h1',
    name: 'Let House',
    area: 'Let House · 海雲台海景',
    nights: 2,
    checkIn: '7/28 (一)',
    checkOut: '7/30 (三)',
    photo: 'haeundae',
    tag: 'Booking.com',
    nearest: '海景房 · 透過 Booking.com 預訂',
    url: 'https://www.booking.com/hotel/kr/let-house.zh-tw.html?label=gen173bo-10CAsofUIJbGV0LWhvdXNlSDBYA2jnAYgBAZgBM7gBF8gBDNgBA-gBAfgBAYgCAZgCAqgCAbgCmtXAzQbAAgHSAiQzYjI0MjQ1Yy0zMTA4LTQ5MGQtYTA2MS1lYzQ4ZTdmMTg1YWTYAgHgAgE&sid=9ccdbb63e97ba7dc6bd2b7601a1749db&aid=304142',
  },
  {
    id: 'h2',
    name: 'Tripmade Annex',
    area: '南浦洞 · Tripmade Annex',
    nights: 5,
    checkIn: '7/30 (三)',
    checkOut: '8/04 (二)',
    photo: 'yongdusan',
    tag: 'Airbnb',
    nearest: '南浦站 (1號線) · 8 人房 · 其餘團員自行安排住宿',
    url: 'https://www.airbnb.com.tw/rooms/1507520587215809349?adults=8&check_in=2026-07-30&check_out=2026-08-04',
  },
];

const DAYS = [
  {
    n: 1, date: '7/28', dow: '一', kind: 'arrival',
    title: '抵達海雲台 · 沙灘漫步',
    base: '海雲台',
    weather: '☀ 29° / 24°',
    photo: 'haeundae',
    summary: '金海機場入境 → 計程車到海雲台民宿 → 海雲台沙灘散步 → 海雲台傳統市場海鮮鍋晚餐',
    stops: [
      { t: '15:30', name: '抵達金海機場 PUS', sub: 'KE2086 · 入境審查 + 領行李 + 換 T-money', icon: 'ic_airplane_fill', tag: '抵達' },
      { t: '16:30', name: '計程車前往海雲台民宿', sub: '11 人建議分 3 台計程車 · 機場→海雲台約 35–45 分 · ₩35,000/台', icon: 'ic_car_line' },
      { t: '17:45', name: 'Let House Check-in', sub: '放行李 · 短暫休息', icon: 'ic_inn_line' },
      { t: '18:30', name: '海雲台沙灘散步', sub: '欣賞韓國海濱代名詞景致 · 看 The Bay 101 夜景', icon: 'ic_location_line', highlight: true },
      { t: '20:00', name: '海雲台傳統市場晚餐', sub: '傳統市場小吃 / 海邊餐廳海鮮鍋任選', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 2, date: '7/29', dow: '二', kind: 'normal',
    title: '海雲台深度體驗',
    base: '海雲台',
    weather: '☀ 30° / 25°',
    photo: 'cheongsapo',
    summary: 'Sky Capsule 尾浦→青沙浦 → 青沙浦海景咖啡 → BUSAN X the SKY 100樓 → 釜山愛麗斯遊艇看廣安大橋夜景',
    stops: [
      { t: '09:00', name: '海雲台藍線公園 Sky Capsule', sub: '尾浦站搭天空膠囊火車前往青沙浦 · 需提前預訂', icon: 'ic_train_line', highlight: true, tag: '需預訂' },
      { t: '11:30', name: '青沙浦海景咖啡廳', sub: '靠海窗景小憩 · 紅白燈塔順遊', icon: 'ic_camera_line' },
      { t: '14:00', name: 'BUSAN X the SKY 100 樓', sub: '俯瞰海雲台全景 · 順訪全球最高星巴克', icon: 'ic_location_line', highlight: true },
      { t: '17:00', name: '回飯店休整 · 早晚餐', sub: '海雲台市場周邊用餐', icon: 'ic_utensils_line' },
      { t: '19:30', name: '釜山愛麗斯遊艇', sub: '海上觀賞廣安大橋夜景 · 建議預訂 11 人包船時段', icon: 'ic_sparkles_fill', highlight: true, tag: '需預訂' },
    ],
  },
  {
    n: 3, date: '7/30', dow: '三', kind: 'transfer',
    title: '機張冒險 · 移宿南浦洞',
    base: '海雲台 → 機張 → 南浦',
    weather: '⛅ 31° / 25°',
    photo: 'yonggungsa',
    summary: '釜山樂天世界校服體驗 → Skyline Luge 斜坡滑車 → 海東龍宮寺 → 帶行李移宿 Tripmade Annex',
    stops: [
      { t: '09:00', name: '退房 · 行李寄送到南浦', sub: 'Let House 寄存或用 LugStay app · 一件約 ₩15,000', icon: 'ic_inn_line', tag: '搬家日' },
      { t: '10:00', name: '機張釜山樂天世界 + 校服租借', sub: '變身高中生在園內拍照玩樂 · 東海線 OSIRIA 站', icon: 'ic_ticket_line', highlight: true, tag: '必玩' },
      { t: '14:00', name: 'Skyline Luge 斜坡滑車', sub: '樂天世界隔壁 · 海景滑車體驗', icon: 'ic_location_line' },
      { t: '16:30', name: '海東龍宮寺', sub: '韓國最美海邊寺廟 · 108 階觀音祈福', icon: 'ic_location_line', highlight: true },
      { t: '19:00', name: '南浦 Tripmade Annex Check-in', sub: '帶著行李移動至南浦洞 · 1 號線南浦站', icon: 'ic_inn_line' },
      { t: '20:30', name: '光復路晚餐', sub: 'Tripmade Annex 樓下即光復路餐廳街', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 4, date: '7/31', dow: '四', kind: 'normal',
    title: '醫美 + 西面購物之旅',
    base: '西面 · Centum',
    weather: '☀ 30° / 25°',
    photo: 'seomyeon',
    summary: '西面醫美 → 松亭三代豬肉湯飯 → 田浦 Strout Coffee → 西面 Olive Young → Centum Spa Land 汗蒸幕',
    stops: [
      { t: '09:30', name: '西面醫美療程', sub: '佰諾佰琪 / 金陽濟皮膚科 · 需提前預訂', icon: 'ic_heart_line', tag: '需預訂' },
      { t: '12:30', name: '西面松亭三代豬肉湯飯', sub: '釜山代表平民料理 · 在地老字號', icon: 'ic_utensils_line' },
      { t: '14:00', name: '田浦咖啡街 · Strout Coffee', sub: '全球百大咖啡廳 · 田浦工業風咖啡街', icon: 'ic_camera_line', highlight: true },
      { t: '16:00', name: '西面商圈 + Olive Young', sub: '美妝補貨 · 地下街韓系服飾', icon: 'ic_store_fill' },
      { t: '19:00', name: 'Spa Land 汗蒸幕 (VBP)', sub: '位於 Centum City · 五星級放鬆療程 · ₩20,000', icon: 'ic_moon_line', highlight: true },
    ],
  },
  {
    n: 5, date: '8/01', dow: '五', kind: 'normal',
    title: '文化村與傳統市場',
    base: '南浦',
    weather: '⛅ 31° / 25°',
    photo: 'gamcheon',
    summary: '甘川文化村找小王子 → 札嘎其市場海鮮 → BIFF 廣場黑糖餅 + 國際市場 → 龍頭山公園釜山塔夜景',
    stops: [
      { t: '09:30', name: '甘川文化村', sub: '找小王子拍照 · 欣賞彩虹小屋 · 蓋章地圖 ₩2,000', icon: 'ic_camera_line', highlight: true, tag: '必去' },
      { t: '13:00', name: '札嘎其市場', sub: '海鮮市場 2F 現點現吃 · 看活海鮮', icon: 'ic_utensils_line' },
      { t: '15:30', name: 'BIFF 廣場 · 國際市場', sub: 'BIFF 黑糖餅必吃 · 國際市場挖寶', icon: 'ic_store_fill' },
      { t: '18:00', name: '龍頭山公園 · 釜山塔', sub: '登塔看 360 度夜景 · 走回 Tripmade Annex', icon: 'ic_sparkles_fill', highlight: true },
      { t: '20:00', name: '韓式炸雞晚餐', sub: '橋村 BHC / 60 雞任選 · 配啤酒看球賽 · 光復路即達', icon: 'ic_utensils_line' },
    ],
  },
  {
    n: 6, date: '8/02', dow: '六', kind: 'normal',
    title: '影島與松島浪漫行',
    base: '影島 + 松島',
    weather: '☀ 30° / 25°',
    photo: 'songdo',
    summary: '影島白淺灘文化村 → 松島海上纜車水晶車廂 → 松島龍宮雲橋 + 太宗台 Danubi → 廣安里無人機表演',
    stops: [
      { t: '09:30', name: '白淺灘文化村', sub: '影島最美海岸線步道 · 彩繪海岸村', icon: 'ic_camera_line', highlight: true },
      { t: '12:30', name: '影島海景午餐', sub: '海岸壁畫旁餐廳 · 鯷魚拌飯', icon: 'ic_utensils_line' },
      { t: '14:00', name: '松島海上纜車', sub: '搭乘水晶車廂看藍綠色大海 · 加價 ₩4,000', icon: 'ic_location_colorwborder', highlight: true },
      { t: '15:30', name: '松島龍宮雲橋', sub: '免費海上步道走到岩礁島', icon: 'ic_location_line' },
      { t: '17:00', name: '太宗台 Danubi 列車', sub: '燈塔環島約 1.5 小時', icon: 'ic_bus_line' },
      { t: '20:00', name: '廣安里無人機表演', sub: '週六晚場 · 沙灘看廣安大橋夜景 · 提前確認時段', icon: 'ic_sparkles_fill', highlight: true, tag: '週六限定' },
    ],
  },
  {
    n: 7, date: '8/03', dow: '日', kind: 'normal',
    title: '最後採買與放鬆',
    base: '南浦',
    weather: '☀ 30° / 24°',
    photo: 'yongdusan',
    summary: '影島 Momos Coffee 悠閒早晨 → 樂天超市南浦店伴手禮大採買 + 退稅 → 韓牛 BBQ 收官晚餐',
    stops: [
      { t: '10:00', name: '影島 Momos Coffee', sub: '世界咖啡師大賽冠軍店 · 享受悠閒早晨', icon: 'ic_camera_line', highlight: true, tag: '冠軍咖啡' },
      { t: '13:00', name: '南浦午餐', sub: '光復路 / 國際市場周邊', icon: 'ic_utensils_line' },
      { t: '14:30', name: '樂天超市 南浦店', sub: '11 人最後伴手禮大採買 · 現場辦理退稅', icon: 'ic_store_fill', highlight: true, tag: '退稅' },
      { t: '18:30', name: '韓牛 BBQ 收官晚餐', sub: '西面 우대포 / 海雲台 수암한우 等專門店 · 11 人務必先訂包廂', icon: 'ic_utensils_line', highlight: true, tag: '必吃' },
      { t: '21:30', name: '回 Tripmade Annex 收行李', sub: '提前打包 · 預訂明早機場接送', icon: 'ic_inn_line' },
    ],
  },
  {
    n: 8, date: '8/04', dow: '一', kind: 'departure',
    title: '早餐與返台',
    base: '南浦 Tripmade Annex',
    weather: '⛅ 28° / 24°',
    photo: 'gimhae',
    summary: 'Egg Drop / Isaac 厚吐司早餐 → 提早 2.5 小時前往金海機場 → KE2085 09:00 飛回台北',
    stops: [
      { t: '05:30', name: 'Egg Drop / Isaac 厚吐司早餐', sub: '韓國最後一頓 · 外帶到機場', icon: 'ic_utensils_line', tag: '出發日' },
      { t: '06:00', name: '退房 · 11 人小巴到金海機場', sub: '南浦 → 機場約 45 分 · 15 人座 mini-bus · ₩120k–160k', icon: 'ic_inn_line' },
      { t: '06:30', name: '抵達金海機場 PUS', sub: '建議起飛前 2.5h 抵達 · 國際線航廈', icon: 'ic_airplane_fill' },
      { t: '07:00', name: '退稅 + 退 T-money 餘額', sub: 'CU/GS25 機台退稅 · T-money 到便利店退', icon: 'ic_coupon_color', tag: '別忘' },
      { t: '09:00', name: '起飛 · 再見釜山', sub: 'KE2085 · 飛行 2h30m', icon: 'ic_airplane_line', highlight: true },
      { t: '10:30', name: '抵達桃園機場 TPE T1', sub: '回到家 · 結束 8 天 7 夜釜山行', icon: 'ic_airplane_fill' },
    ],
  },
];

Object.assign(window, { TRIP, HOTELS, DAYS });
